import { randomUUID } from "node:crypto";

import { createVoiceClient } from "@creative-ai/voice-client";

function voiceClient() {
  const baseUrl = process.env.BYTEPLUS_VOICE_BASE_URL;
  return createVoiceClient({
    apiKey: process.env.BYTEPLUS_VOICE_API_KEY || "",
    ...(baseUrl ? { baseUrl } : {}),
  });
}

export interface CloneVoiceOutcome {
  speakerId: string;
  raw: unknown;
}

// Unlike the other three Voice features, tts/voice_clone's response shape has not been
// live-confirmed yet -- cloning consumes the account's separate, limited "Voice
// Replication" quota (unlike TTS/ASR, which are cheap to re-test), so this wasn't
// diagnosed with a throwaway test call the way the others were. The speaker ID is
// generated by us and passed in the request, so it's always known regardless of what
// the response actually contains -- only `raw` is unconfirmed, and is returned as-is
// for the caller to inspect until a real response is observed and this can be
// tightened up.
export async function cloneVoiceFromAudio(
  userId: string,
  wavBytes: Uint8Array,
): Promise<CloneVoiceOutcome> {
  const speakerId = `${userId.slice(0, 8)}-${randomUUID().slice(0, 8)}`;
  const base64 = Buffer.from(wavBytes).toString("base64");

  const raw = await voiceClient().cloneVoice({
    speaker_id: speakerId,
    audio: { data: base64, format: "wav" },
    language: 1,
    extra_params: { demo_text: "Hello, this is a preview of your cloned voice." },
  });

  return { speakerId, raw };
}
